//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvccrudoperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_master
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public Nullable<int> product_category { get; set; }
        public string category_name { get; set; }
    }
}
